import { Inter } from "next/font/google";
import "./globals.css";

export const inter = Inter({
	subsets: ["latin"],
	display: "swap",
});

export const metadata = {
	title: "Encuentralo",
	description: "Generated by Encuentralo",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={inter.className}>
			<head>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
				/>
			</head>
			<body>{children}</body>
		</html>
	);
}
